{{- if not (include "orchestrator.isValueFrom" .Values.global.secrets.encryptionKey) }}
---
{{- $secretName := (printf "%s-encryption-key" .Release.Name) }}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existing (hasKey $existing.data "AES_256_KEY") }}
  AES_256_KEY: {{ index $existing.data "AES_256_KEY" }}
  {{- else }}
  AES_256_KEY: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
{{- end }}
{{- if not (include "orchestrator.isValueFrom" .Values.global.secrets.authSecret) }}
---
{{- $secretName := (printf "%s-auth-secret" .Release.Name) }}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existing (hasKey $existing.data "AUTH_SECRET") }}
  AUTH_SECRET: {{ index $existing.data "AUTH_SECRET" }}
  {{- else }}
  AUTH_SECRET: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
{{- end }}
