{{- if eq .Values.global.cloudProvider "gcp" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-weave-trace-backend-config
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
spec:
  {{- if .Values.global.gcpSecurityPolicy }}
  securityPolicy:
    name: {{ .Values.global.gcpSecurityPolicy }}
  {{- end }}
  timeoutSec: 120
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "weaveTrace.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.labels" . | nindent 4 }}
    {{- include "weaveTrace.commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if eq .Values.global.cloudProvider "aws" }}
    alb.ingress.kubernetes.io/healthcheck-path: /traces/health
    {{- end }}
    {{- if eq .Values.global.cloudProvider "gcp" }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ $.Release.Name }}-weave-trace-backend-config"}'
    {{- end }}
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8722
      targetPort: 8080
      protocol: TCP
      name: weave-trace
  selector:
    {{- include "weaveTrace.labels" . | nindent 4 }}
