{{- if .Values.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.clusterRole.enabled}}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
metadata:
  name: {{ include "console.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "console.commonLabels" . | nindent 4 }}
    {{- include "console.labels" . | nindent 4 }}
    {{- if .Values.clusterRole.labels -}}
    {{-   toYaml .Values.clusterRole.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.clusterRole.annotations -}}
    {{-   toYaml .Values.clusterRole.annotations | nindent 4 }}
    {{- end }}
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "watch", "patch", "create" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces", "pods", "pods/log", "configmaps", "services", "serviceaccounts", "events" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "statefulsets", "daemonsets", "replicasets", "controllerrevisions" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments/status", "statefulsets/status", "daemonsets/status", "replicasets/status" ]
    verbs: [ "get" ]
  - apiGroups: [ "apps.wandb.com" ]
    resources: [ "weightsandbiases" ]
    verbs: [ "get" ]
{{- end }}
