apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.clusterRole.enabled}}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ include "console.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "console.commonLabels" . | nindent 4 }}
    {{- include "console.labels" . | nindent 4 }}
    {{- if .Values.clusterRole.labels -}}
    {{-   toYaml .Values.clusterRole.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.clusterRole.annotations -}}
    {{-   toYaml .Values.clusterRole.annotations | nindent 4 }}
    {{- end }}
roleRef:
  {{- if .Values.clusterRole.enabled}}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "console.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "console.fullname" . }}
    namespace: {{ .Release.Namespace }}
