{{- if eq .Values.global.cloudProvider "gcp" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-console-backend-config
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
spec:
  {{- if .Values.global.gcpSecurityPolicy }}
  securityPolicy:
    name: {{ .Values.global.gcpSecurityPolicy }}
  {{- end }}
  timeoutSec: 120
{{- end }}
---
{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "console.labels" . | nindent 4 }}
    {{- include "console.commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if eq .Values.global.cloudProvider "gcp" }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ $.Release.Name }}-console-backend-config"}'
    {{- end }}
    {{- if eq .Values.global.cloudProvider "aws" }}
    alb.ingress.kubernetes.io/healthcheck-path: /console/api/ready
    {{- end }}
    {{- include "wandb.serviceAnnotations" $ | nindent 4 }}
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8082
      protocol: TCP
      name: console
  selector:
    {{- include "console.labels" . | nindent 4 }}
{{- end }}
