apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-executor-configmap
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-executor-secret
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
type: Opaque
data: {}