apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flat-run-fields-updater-configmap
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  GORILLA_FILE_HOST: "{{ .Values.global.host }}"

  GORILLA_RUN_UPDATE_QUEUE_ADDR: "internal://"
  GORILLA_RUN_UPDATE_SHADOW_QUEUE_OVERFLOW_BUCKET_NAME: "wandb"
  GORILLA_RUN_UPDATE_SHADOW_QUEUE_OVERFLOW_BUCKET_PREFIX: "wandb-overflow"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-flat-run-fields-updater-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data: {}

