apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-configmap
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
{{- if not .Values.app.install }}
  FRONTEND_APP_BACKEND: "{{ .Release.Name }}-api:8081"
  FRONTEND_AUTH_BACKEND: "{{ .Release.Name }}-api:8081"

  # this doesn't actually work, but the FE pod currently requires this host to be valid
  FRONTEND_LOCAL_BACKEND: "{{ .Release.Name }}-api:8083"
{{- else }}
  FRONTEND_APP_BACKEND: "{{ .Release.Name }}-app:8080"
  FRONTEND_AUTH_BACKEND: "{{ .Release.Name }}-app:8080"
  FRONTEND_LOCAL_BACKEND: "{{ .Release.Name }}-app:8083"
{{- end }}
  FRONTEND_WEAVE_BACKEND: "{{ .Release.Name }}-weave:9994"
  REACT_APP_GIT_TAG: "HEAD"
  REACT_APP_HOST: "{{ .Values.global.host }}"
  REACT_APP_ENVIRONMENT_NAME: "local"
  REACT_APP_ENVIRONMENT_IS_PRIVATE: "true"
  REACT_APP_ANALYTICS_DISABLED: "true"
  WEAVE_TRACES_ENABLED: '{{ index .Values.global "weave-trace" "enabled" }}'
  SERVER_FLAG_WEAVE_1_PERCENTAGE: "100"
  WEAVE_ENABLED: "true"
  OPERATOR_ENABLED: "true"
