apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-configmap
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  PUBLIC_URL: "{{ .Values.global.host }}"
  REACT_APP_GIT_TAG: "HEAD"
  REACT_APP_HOST: "{{ .Values.global.host }}"
  REACT_APP_ENVIRONMENT_NAME: "local"
  REACT_APP_ENVIRONMENT_IS_PRIVATE: "true"
  REACT_APP_ANALYTICS_DISABLED: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
stringData: {} 
