apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gorilla-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
stringData:
  {{- if ne .Values.global.email.smtp.host "" }}
  GORILLA_EMAIL_SINK: "smtp://{{ .Values.global.email.smtp.user }}:{{ .Values.global.email.smtp.password }}@{{ .Values.global.email.smtp.host }}:{{ .Values.global.email.smtp.port }}"
  {{- else }}
  GORILLA_EMAIL_SINK: "https://api.wandb.ai/email/dispatch"
  {{- end }}
  SLACK_SECRET: {{ default "" .Values.global.slack.secret }}
  {{- if ne .Values.global.auth.oidc.clientId ""  }}
  GORILLA_OIDC_CLIENT_SECRET: {{ .Values.global.auth.oidc.secret }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gorilla-configmap
  labels:
      {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  BANNERS: {{ toJson .Values.global.banners | quote }}
  OPERATOR_ENABLED: 'true'
  LOGGING_ENABLED: 'true'
  {{- if ne .Values.global.auth.oidc.clientId ""  }}
  GORILLA_OIDC_CLIENT_ID: {{ .Values.global.auth.oidc.clientId }}
  GORILLA_OIDC_AUTH_METHOD: {{ .Values.global.auth.oidc.authMethod }}
  GORILLA_OIDC_ISSUER: {{ .Values.global.auth.oidc.issuer }}
  {{- end }}
  GORILLA_SESSION_LENGTH: "{{ .Values.global.auth.sessionLengthHours }}h"
  {{- if and .Values.global .Values.global.observability }}
    {{- if eq (default "custom" .Values.global.observability.mode) "otel" }}
  GORILLA_STATSD_PORT: "8125"
  GORILLA_STATSD_HOST: "0.0.0.0"
    {{- end }}
  {{- end }}
  WEAVE_SERVICE: "{{ .Release.Name }}-weave:9994"
  PARQUET_HOST: "http://{{ .Release.Name }}-parquet:8087"
  PARQUET_ENABLED: "true"
  {{- if index .Values.global "weave-trace" "enabled" }}
  WEAVE_TRACES_ENABLED: "true"
  {{- end }}
  {{- if .Values.extraCors }}
  GORILLA_CORS_ORIGINS: "{{ join "," .Values.extraCors }}"
  {{- end }}
  GORILLA_SWEEP_PROVIDER: "{{ .Values.global.sweepProvider | default (printf "http://%s-app:8082" .Release.Name) }}"
  GORILLA_COREWEAVE_OBSERVABILITY_API_KEY: {{ .Values.global.coreweave.observabilityApiKey | quote }}
  WANDB_BASE_URL: "{{ .Values.global.baseUrl | default (printf "http://%s-app:8081" .Release.Name) }}"
  GORILLA_VIEW_SPEC_UPDATER_EXECUTABLE: "/usr/local/bin/view-spec-updater-linux"
  GORILLA_LIMITER: "noop://"
  GORILLA_PARQUET_RPC_PATH: "/_goRPC_"
  GORILLA_SCHEMA_FILE: "/schema.graphql"
  GORILLA_PORT: "8081"
  GORILLA_ACTIVITY_STORE_ENABLE: "true"
  GORILLA_GLUE_TASK_STORE: "memory://"
  GORILLA_COLLECT_AUDIT_LOGS: "true"
  GORILLA_USE_PARQUET_HISTORY_STORE: "true"
  GORILLA_PARQUET_PORT: "8087"
  GORILLA_PARQUET_ARROW_BUFFER_SIZE: "2147483648" # 2GB
  GORILLA_RUN_UPDATE_QUEUE_ADDR: "internal://"
  GORILLA_FILE_STORE_IS_PROXIED: "false"
  GORILLA_ACTIVITY_STORE_SERVE: "true"
  GORILLA_GLUE_TASK_CONFIG_PATH: "/gorilla_glue_tasks_local.yaml"
  GORILLA_ONPREM: "true"
  GORILLA_STATSD_PORT: "8125"
  GORILLA_ACTIVITY_STORE_BACKFILL_ENABLE: "true"
  GORILLA_ARTIFACT_GC_ENABLED: "false"
  GORILLA_GLUE_TASK_PROVIDER: "memory://"
  GORILLA_DEFAULT_REGION: "minio-local"
  {{- if .Values.global.executor.enabled }}
  GORILLA_TASK_QUEUE_WORKER_ENABLED: "false"
  {{- else }}
  GORILLA_TASK_QUEUE_WORKER_ENABLED: "false"
  {{- end }}
