{{- if not .Values.global.licenseSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wandb.license.name" . }}
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  {{ include "wandb.license.key" . }}: "{{ .Values.global.license }}"
{{- end }}
