{{- if .Values.global.lumen.install -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-lumen-configmap
data:
  LUMEN_AGENT_CONFIG_PATH: "{{ include "wandb.lumen.rulePath" . }}"
  LUMEN_CUSTOMER_NAME: "{{ .Release.Name }}"
  LUMEN_DATA_ROOT: "{{ include "wandb.lumen.dataRoot" . }}"
  LUMEN_STAGING_ROOT: "file://{{ include "wandb.lumen.stagingPath" . }}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-lumen-rules
data:
  managed-install.yaml: |
    keyRuleSets:
      - name: k8s-metadata-noise
        keyRules:
          - keyRegex: "^metadata__managedFields"
          - keyRegex: "^metadata__resourceVersion$"
          - keyRegex: "^metadata__uid$"
          - keyRegex: "^metadata__generation$"
          - keyRegex: "^metadata__creationTimestamp$"
          - keyRegex: "^metadata__selfLink$"
          - keyRegex: "^metadata__annotations__kubectl\\.kubernetes\\.io/last-applied-configuration$"
          - keyRegex: "^status$"
          - keyRegex: "^status__"
      - name: k8s-pod-noise
        keyRules:
          - keyRegex: "^spec__(containers|initContainers)__[^_]+__env__"
          - keyRegex: "^spec__(containers|initContainers)__[^_]+__envFrom__"
          - keyRegex: "^spec__(containers|initContainers)__[^_]+__volumeMounts__"
          - keyRegex: "^spec__containers__[^_]+__(startup|liveness|readiness)Probe__"
          - keyRegex: "^spec__tolerations"
          - keyRegex: "^spec__topology"
          - keyRegex: "^spec__volumes"
          - keyRegex: "^status$"
          - keyRegex: "^status__"
      - name: standard-redactions
        keyRules:
          - keyRegex: "secret"
            ignoreCase: true
          - keyRegex: "password"
            ignoreCase: true
          - keyRegex: "key$"
            ignoreCase: true
          - keyRegex: "token$"
            ignoreCase: true
          - keyRegex: "license$"
            ignoreCase: true
          - keyRegex: "cert$"
            ignoreCase: true

    scrapers:
      - name: wandb-configmaps
        connection:
          kubernetes:
            discover:
              kind: ConfigMap
              namespace: {{ .Release.Namespace }}
              nameRegex: "^wandb-.*-configmap$"
        prune:
          keyRules:
            - use: [ k8s-metadata-noise ]
            - keyRegex: "apiVersion"
        redact:
          keyRules:
            - use: [ standard-redactions ]
          valueHooks:
            - URIPassword

      - name: wandb-secrets
        connection:
          kubernetes:
            discover:
              kind: Secret
              namespace: {{ .Release.Namespace }}
              nameRegex: "^wandb-(bucket|clickhouse|global|gorilla|internal-signer|kafka|license|mysql|parquet|redis|smtp)"
              nameExceptions:
                - "-backup"
        prune:
          keyRules:
            - use: [ k8s-metadata-noise ]
            - keyRegex: "type"
            - keyRegex: "apiVersion"
        redact:
          keyRules:
            - use: [ standard-redactions ]
          valueHooks:
            - URIPassword

      - name: wandb-pods
        connection:
          kubernetes:
            discover:
              kind: Pod
              namespace: {{ .Release.Namespace }}
              nameRegex: "^wandb-(anaconda2|api|app|executor|filemeta|flat-run-fields-updater|frontend|glue|parquet|weave).*"
        prune:
          keyRules:
            - use: [ k8s-metadata-noise, k8s-pod-noise ]
        redact:
          keyRules:
            - use: [ standard-redactions ]
          valueHooks:
            - URIPassword

      - name: wandb-pull-with-httpget
        connection:
          kubernetes:
            discover:
              kind: Pod
              namespace: {{ .Release.Namespace }}
              annotations:
                - key: lumen.wandb.ai/agent
                  value: "true"
            pull:
              type: k8sHttpGet
              httpGet:
                portName: http
                listPath: /lumen/list
        prune:
          keyRules:
            - use: [ k8s-metadata-noise ]
            - keyRegex: "apiVersion"
        redact:
          keyRules:
            - use: [ standard-redactions ]
          valueHooks:
            - URIPassword

      - name: wandb-specs
        connection:
          kubernetes:
            discover:
              kind: Secret
              namespace: {{ .Release.Namespace }}
              nameRegex: "wandb-spec-(active|user)$"
        prune:
          keyRules:
            - use: [ k8s-metadata-noise ]
            - keyRegex: "status"
            - keyRegex: "apiVersion"
        redact:
          keyRules:
            - use: [ standard-redactions ]
          valueHooks:
            - URIPassword

      - name: wandb-cr
        connection:
          kubernetes:
            discover:
              kind: WeightsAndBiases
              namespace: {{ .Release.Namespace }}
        prune:
          keyRules:
            - use: [ k8s-metadata-noise ]
            - keyRegex: "status"
            - keyRegex: "apiVersion"
        redact:
          keyRules:
            - use: [ standard-redactions ]
          valueHooks:
            - URIPassword

---

{{- if include "operator-wandb.lumen.audience" . }}
{{- $audience := include "operator-wandb.lumen.audience" . -}}
# WIF only needed for lumen dataRoot, not when using standard wandb-bucket
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-lumen-gcp-wif
data:
  credential-config.json: |
    {
      "type": "external_account",
      "audience": {{ $audience | quote }},
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/secrets/tokens/gcp-ksa/token",
        "format": { "type": "text" }
      }
    }

{{- end }}

{{- end }}
