{{if .Values.global.lumen.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-lumen-configmap
  labels:
      {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  LUMEN_CONFIG_PATH: "/app/definitions/collector/managed-install.yaml"
  LUMEN_SNAPSHOT_PREFIX: "{{ .Values.global.lumen.snapshotPrefix | default "snapshot" }}"
  LUMEN_CUSTOMER_NAME: "{{ .Release.Name }}"
  LUMEN_DATA_ROOT: {{ required "global.lumen.bucket is required when global.lumen.enabled is true" .Values.global.lumen.lumenDataRoot | quote }}
{{- end }}
