apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-lumen-configmap
  labels:
      {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  LUMEN_CONFIG_PATH: "/app/definitions/collector/managed-install.yaml"
  LUMEN_SNAPSHOT_PREFIX: "{{ .Values.global.lumen.snapshotPrefix | default "snapshot" }}"
  LUMEN_CUSTOMER_NAME: "{{ .Release.Name }}"
  LUMEN_AGENT_EXPORT_ROOT: "{{ .Values.global.lumen.agentExportRoot }}"
  LUMEN_PARQUET_ROOT: "{{ .Values.global.lumen.parquetRoot }}"
  LUMEN_PROCESSOR_COMPLETED_ROOT: "{{ .Values.global.lumen.processorCompletedRoot }}"
  LUMEN_PROCESSOR_INBOUND_ROOT: "{{ .Values.global.lumen.processorInboundRoot }}"