{{- if .Values.global.mysql.rdsIamAuth -}}
  {{- if empty .Values.global.mysql.host -}}
    {{- fail "global.mysql.host is required when global.mysql.rdsIamAuth=true" -}}
  {{- end -}}
  {{- if empty .Values.global.mysql.user -}}
    {{- fail "global.mysql.user is required when global.mysql.rdsIamAuth=true" -}}
  {{- end -}}
  {{- if empty .Values.global.mysql.awsRegion -}}
    {{- fail "global.mysql.awsRegion is required when global.mysql.rdsIamAuth=true" -}}
  {{- end -}}
  {{- if empty .Values.global.mysql.caCert -}}
    {{- fail "global.mysql.caCert is required when global.mysql.rdsIamAuth=true" -}}
  {{- end -}}
  {{- if not (empty .Values.global.mysql.password) -}}
    {{- fail "global.mysql.password must be empty when global.mysql.rdsIamAuth=true" -}}
  {{- end -}}
  {{- if not (empty .Values.global.mysql.passwordSecret.name) -}}
    {{- fail "global.mysql.passwordSecret.name must be empty when global.mysql.rdsIamAuth=true" -}}
  {{- end -}}
  {{- if .Values.mysql.install -}}
    {{- fail "mysql.install must be false when global.mysql.rdsIamAuth=true" -}}
  {{- end -}}
  {{- if (index .Values.app.initContainers "init-db").enabled -}}
    {{- fail "app.initContainers.init-db.enabled must be false when global.mysql.rdsIamAuth=true" -}}
  {{- end -}}
  {{- if (index .Values.prometheus "mysql-exporter").install -}}
    {{- fail "prometheus.mysql-exporter.install must be false when global.mysql.rdsIamAuth=true" -}}
  {{- end -}}
{{- end -}}
