apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-configmap
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /tmp/nginx.pid;


    events {
        worker_connections  1024;
    }

    http {
      server {
        listen 8080;
        proxy_set_header Host $host:8080;
        client_max_body_size 0;
        location / {
          proxy_pass http://{{ .Release.Name }}-app:8080;
        }
        location /console {
          proxy_pass http://{{ .Release.Name }}-console:8082;
        }
      {{- if .Values.global.api.enabled }}
        {{- if .Values.global.api.additionalPaths.analytics }}
        location /analytics {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}

        {{- if .Values.global.api.additionalPaths.analytics }}
        location /analytics {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}

        location /api {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- if .Values.global.api.additionalPaths.artifacts }}
        location /artifacts {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }

        location /artifactsV2 {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}

        {{- if .Values.global.api.additionalPaths.admin }}
        location /admin/audit_logs {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}

        {{- if .Values.global.api.additionalPaths.debug }}
        location /debug {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}

        {{- if .Values.global.api.additionalPaths.files }}
        location /files {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}

        location /graphql {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }

        location /graphql2 {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }

        {{- if .Values.global.api.additionalPaths.oidc }}
        location /oidc {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}

        {{- if .Values.global.api.additionalPaths.proxy }}
        location /proxy {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}

        {{- if .Values.global.api.additionalPaths.scim }}
        location /scim {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}

        {{- if .Values.global.api.additionalPaths.service_dangerzone }}
        location /service-dangerzone {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}

        {{- if .Values.global.api.additionalPaths.service_redirect }}
        location /service-redirect {
          proxy_pass http://{{ .Release.Name }}-api:8081;
        }
        {{- end }}
      {{- end }}

        {{- if (get .Values "weave-trace").install }}
        location /traces {
          proxy_pass http://{{ .Release.Name }}-weave-trace:8722;
        }
        {{- end }}

        {{- range $path, $service := .Values.nginx.additionalServices }}
        location /{{ $path }} {
          {{- range $header, $value := $service.headers }}
          proxy_set_header {{ $header }} {{ $value }};
          {{- end }}
          proxy_pass {{ $service.host }};
        }
        {{- end }}
      }
    }
