apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-parquet-configmap
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  # Port configuration
  GORILLA_PARQUET_PORT: "8087"
  
  # RPC path configuration
  GORILLA_PARQUET_RPC_PATH: "/_goRPC_"
  # Task queue configuration
  GORILLA_TASK_QUEUE_WORKER_ENABLED: "false"
  
  # Parquet-specific configuration
  GORILLA_USE_PARQUET_HISTORY_STORE: "true"
  GORILLA_PARQUET_ARROW_BUFFER_SIZE: "2147483648" # 2GB
  GORILLA_COLLECT_AUDIT_LOGS: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-parquet-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data: {}
