{{- if index .Values "parquet-metadata-cache" "install" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-parquet-metadata-cache-configmap
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  GORILLA_PARQUET_METADATA_CACHE_PORT: "9091"
  GORILLA_MAX_CACHE_BYTES: {{ index .Values "parquet-metadata-cache" "maxCacheBytes" | default "4000000000" | quote }}
  GORILLA_LOG_FORMAT: "json"
  GORILLA_PPROF_PORT: "8081"
  GORILLA_FILE_HOST: {{ .Values.global.host | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-parquet-metadata-cache-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data: {}
{{- end }}
