{{- if index .Values "parquet-headless" "install" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-parquet-headless-configmap
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
{{ include "operator-wandb.parquetConfigMapData" . | nindent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-parquet-headless-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data: {}
{{- end }}
