apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-parquet-configmap
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  # Port configuration
  GORILLA_PARQUET_PORT: "8087"
  
  # RPC path configuration
  GORILLA_PARQUET_RPC_PATH: "/_goRPC_"
  # Task queue configuration
  GORILLA_TASK_QUEUE_WORKER_ENABLED: "false"
  
  # Parquet-specific configuration
  GORILLA_USE_PARQUET_HISTORY_STORE: "true"
  GORILLA_PARQUET_ARROW_BUFFER_SIZE: "2147483648" # 2GB
  
  # General application configuration
  GORILLA_FILE_STORE_IS_PROXIED: "false"
  GORILLA_COLLECT_AUDIT_LOGS: "true"
  
  # Monitoring and observability
  {{- if and .Values.global .Values.global.observability }}
    {{- if eq (default "custom" .Values.global.observability.mode) "otel" }}
  GORILLA_STATSD_PORT: "8125"
  GORILLA_STATSD_HOST: "0.0.0.0"
    {{- else }}
  GORILLA_STATSD_PORT: "8125"
    {{- end }}
  {{- else }}
  GORILLA_STATSD_PORT: "8125"
  {{- end }}
  
  # T-shirt size configuration
  GORILLA_TSHIRT_SIZE: {{ .Values.global.size | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-parquet-secret
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
stringData:
  {{- if ne .Values.global.email.smtp.host "" }}
  GORILLA_EMAIL_SINK: "smtp://{{ .Values.global.email.smtp.user }}:{{ .Values.global.email.smtp.password }}@{{ .Values.global.email.smtp.host }}:{{ .Values.global.email.smtp.port }}"
  {{- else }}
  GORILLA_EMAIL_SINK: "https://api.wandb.ai/email/dispatch"
  {{- end }}
  SLACK_SECRET: {{ default "" .Values.global.slack.secret }}
  {{- if and (not .Values.global.licenseSecret.name) (not .Values.global.licenseSecret.key) .Values.global.license }}
  LICENSE: {{ .Values.global.license }}
  GORILLA_LICENSE: {{ .Values.global.license }}
  {{- end }}
  {{- if ne .Values.global.auth.oidc.clientId ""  }}
  GORILLA_OIDC_CLIENT_SECRET: {{ .Values.global.auth.oidc.secret }}
  {{- end }}