# Create internal password secret only when registrySearch is enabled
# and password is not already provided as a K8s reference map
{{- if and .Values.global.registrySearch.enabled (not (kindIs "map" .Values.global.registrySearch.password)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wandb.registrySearch.internalSecretName" . | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
    "reflector.v1.k8s.emberstack.com/reflection-allowed": "true"
    "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
    "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "{{ .Release.Name }}-.*"
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  {{ include "wandb.registrySearch.internalSecretKey" . }}: {{ include "wandb.registrySearch.password" . | b64enc }}
{{- end }}
