apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-weave-configmap
  labels:
      {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  GORILLA_ONPREM: "true"
  PORT: "9994"
  WANDB_BASE_URL: "http://{{ .Release.Name }}-app:8080/"
  WANDB_PUBLIC_BASE_URL: "{{ .Values.global.host }}"
  WEAVE_LOG_FORMAT: "json"
  WEAVE_SERVER_NUM_WORKERS: "4"
  WEAVE_SERVER_URL: "http://127.0.0.1:9994"
  GORILLA_TSHIRT_SIZE: {{ .Values.global.size | quote }}
  WEAVE_LOCAL_ARTIFACT_DIR: "/vol/weave/cache"
  WEAVE_CACHE_CLEAR_INTERVAL: "{{ .Values.weave.cache.intervalInHours }}"