{{- if index .Values "weave-trace" "install" }}
  {{- $weaveTrace := index .Values "weave-trace" | default dict -}}
  {{- $serviceAccount := $weaveTrace.serviceAccount | default dict -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wandb.weaveTraceServiceAccountName" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
  {{- with $serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
