_wandb:
    value:
        cli_version: 0.21.1
        e:
            3mqfpo6mzgsrlym91yozmicqt4y8aqwi:
                args:
                    - verify
                email: peyton.sarmiento@wandb.com
                executable: /Users/peytonsarmiento/.pyenv/versions/3.11.6/bin/python3.11
                host: Peyton-Sarmiento-H4QDYT9T4Y
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/peytonsarmiento/.pyenv/versions/3.11.6/bin/wandb
                python: CPython 3.11.6
                root: /Users/peytonsarmiento/helm-charts
                startedAt: "2025-08-22T20:55:41.041558Z"
                writerId: 3mqfpo6mzgsrlym91yozmicqt4y8aqwi
        m: []
        python_version: 3.11.6
        t:
            "3":
                - 2
                - 3
                - 14
                - 16
            "4": 3.11.6
            "5": 0.21.1
            "10":
                - 20
            "12": 0.21.1
            "13": darwin-arm64
test:
    value: put to graphql
