{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weaveTrace.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" $ | nindent 6 }}
      {{- include "weaveTrace.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wandb.podLabels" . | nindent 8 }}
        {{- include "weaveTrace.commonLabels" . | nindent 8 }}
        {{- include "weaveTrace.podLabels" . | nindent 8 }}
        {{- include "weaveTrace.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.weave-trace.hostNetwork }}
      {{- toYaml .Values.weave-trace.hostNetwork | nindent 6 }}
      {{- end }}
      {{- include "wandb.nodeSelector" . | nindent 6 }}
      {{- include "wandb.priorityClassName" . | nindent 6 }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      {{- if not .Values.migration.useHook }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: {{ include "weaveTraceMigrate.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - "python"
            - "migrator.py"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-clickhouse-configmap
          env:
            - name: WF_CLICKHOUSE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "wandb.clickhouse.passwordSecret" . }}
                  key: {{ .Values.global.clickhouse.passwordSecret.passwordKey }}
            {{- include "weaveTrace.extraEnv" (dict "global" .Values.global "local" .Values) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ include "weaveTrace.fullname" .  }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- include "wandb.containerSecurityContext" .Values.container.securityContext | nindent 10 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-clickhouse-configmap
          env:
            - name: PORT
              value: "8080"
            - name: API_PATH_PREFIX
              value: "/traces"
            - name: WANDB_PUBLIC_BASE_URL
              value: {{ .Values.global.host }}
            - name: WANDB_BASE_URL
              value: http://{{ .Release.Name }}-app:8080/
            - name: GORILLA_TSHIRT_SIZE
              value: {{ .Values.global.size | quote }}
            - name: WF_TRACE_SERVER_URL
              value: "{{ .Values.global.host }}/traces"
            - name: WF_ENFORCE_PASSWORD_LENGTH
              value: "false"
            - name: WF_CLICKHOUSE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "wandb.clickhouse.passwordSecret" . }}
                  key: {{ .Values.global.clickhouse.passwordSecret.passwordKey }}
            {{- include "weaveTrace.extraEnv" (dict "global" .Values.global "local" .Values) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          {{- if not .Values.datadog.enabled }}
          command:
            - uvicorn
          args:
            - "src.trace_server:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8080"
          {{- end }}
          livenessProbe:
            httpGet:
              path: /traces/health
              port: http
            timeoutSeconds: 2
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /traces/health
              port: http
            timeoutSeconds: 2
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /traces/health
              port: http
            failureThreshold: 12
            periodSeconds: 10
          volumeMounts:
            - name: weave-trace-internal-jwt
              mountPath: /tmp/weave-trace/internal-jwt    
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ include "weaveTrace.serviceAccountName" . }}
      volumes:
        - name: weave-trace-internal-jwt
          projected:
            sources:
              - serviceAccountToken:
                  audience: internal-service
                  path: token
                  expirationSeconds: 600
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name:  {{ include "weaveTrace.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "weaveTrace.fullname" . }}
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
