{{- if .Values.weaveWorker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weaveWorker.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.commonLabels" . | nindent 4 }}
    {{- include "weaveTrace.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" $ | nindent 6 }}
      {{- include "weaveTrace.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wandb.podLabels" . | nindent 8 }}
        {{- include "weaveTrace.commonLabels" . | nindent 8 }}
        {{- include "weaveTrace.podLabels" . | nindent 8 }}
        {{- include "weaveTrace.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- include "wandb.nodeSelector" . | nindent 6 }}
      {{- include "wandb.priorityClassName" . | nindent 6 }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: {{ include "weaveWorker.fullname" .  }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- include "wandb.containerSecurityContext" .Values.container.securityContext | nindent 10 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-clickhouse-configmap
          env:
            - name: WF_CLICKHOUSE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "wandb.clickhouse.passwordSecret" . }}
                  key: {{ .Values.global.clickhouse.passwordSecret.passwordKey }}
            - name: WF_KAFKA_BROKER_HOST
              value: "{{ .Values.bufstream.host }}"
            - name: WF_KAFKA_BROKER_PORT
              value: "{{ .Values.bufstream.port }}"
            {{- include "weaveTrace.extraEnv" (dict "global" .Values.global "local" .Values) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
            - name: WANDB_INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: weave-worker-auth
                  key: key
            - name: WANDB_INTERNAL_SERVICE_TOKEN_SECRET_NAME
              value: weave-worker-auth
            - name: WANDB_BASE_URL
              value: http://{{ .Release.Name }}-app:8080/
            - name: WEAVE_ENABLE_ONLINE_EVAL
              value: "true"
            - name: WEAVE_TRACE_SERVER_BASE_URL
              value: "{{ .Values.global.host }}/traces"
          command:
            - python
          args:
            - "-m"
            - "src.workers.scoring_worker"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
