apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-search-settings-user-defined
data:
  user: "default"
  database: "registry_search"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-search-password-user-defined
type: Opaque
stringData:
  password: "user-defined-registry-search-password"
