apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-search-settings-user-defined
data:
  host: "clickhouse.user-defined.example.com"
  port: "8123"
  user: "ch-admin"
  database: "registry_search"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-search-password-user-defined
type: Opaque
stringData:
  password: "user-defined-registry-search-password"
