{{- if .Values.enabled }}
{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-exporter.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "mysql-exporter.commonLabels" . | nindent 4 }}
    {{- include "mysql-exporter.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" $ | nindent 6 }}
      {{- include "mysql-exporter.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wandb.podLabels" . | nindent 8 }}
        {{- include "mysql-exporter.commonLabels" . | nindent 8 }}
        {{- include "mysql-exporter.podLabels" . | nindent 8 }}
        {{- include "mysql-exporter.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
    spec:
      {{- include "wandb.tolerations" . | nindent 6 }}
      {{- include "wandb.nodeSelector" . | nindent 6 }}
      {{- include "wandb.priorityClassName" . | nindent 6 }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - --mysqld.address=$(MYSQL_HOST):$(MYSQL_PORT)
            - --mysqld.username=$(MYSQL_USER)
          ports:
            - name: exporter
              containerPort: 9104
              protocol: TCP
          env:
            {{- if kindIs "map" .Values.global.mysql.password -}}
            - name: MYSQL_PASSORD
            {{- toYaml .Values.global.mysql.password | nindent 14 }}
            {{- else }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wandb.mysql.passwordSecret" . | quote}}
                  key: "{{ .Values.global.mysql.passwordSecret.passwordKey }}"
            {{- end }}

            {{- if kindIs "map" .Values.global.mysql.port -}}
            - name: MYSQL_PORT
            {{ toYaml .Values.global.mysql.port | nindent 14 }}
            {{- else }}
            - name: MYSQL_PORT
              value: "{{ include "wandb.mysql.port" . }}"
            {{- end }}

            {{- if kindIs "map" .Values.global.mysql.host -}}
            - name: MYSQL_HOST
            {{- toYaml .Values.global.mysql.host | nindent 14 }}
            {{- else }}
            - name: MYSQL_HOST
              value: "{{ include "wandb.mysql.host" . }}"
            {{- end }}

            {{- if kindIs "map" .Values.global.mysql.database -}}
            - name: MYSQL_DATABASE
            {{- toYaml .Values.global.mysql.database | nindent 14 }}
            {{- else }}
            - name: MYSQL_DATABASE
              value: "{{ include "wandb.mysql.database" . }}"
            {{- end }}

            {{- if kindIs "map" .Values.global.mysql.user -}}
            - name: MYSQL_USER
            {{- toYaml .Values.global.mysql.user | nindent 14 }}
            {{- else }}
            - name: MYSQL_USER
              value: "{{ include "wandb.mysql.user" . }}"
            {{- end -}}

            - name: MYSQL
              value: "mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@$(MYSQL_HOST):$(MYSQL_PORT)/$(MYSQL_DATABASE)"

            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wandb.mysql.passwordSecret" . }}
                  key:  {{ .Values.global.mysql.passwordSecret.passwordKey }}

            {{- include "mysql-exporter.extraEnv" (dict "global" $.Values.global "local" .Values) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: exporter
          readinessProbe:
            httpGet:
              path: /
              port: exporter

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if ne (include "wandb.redis.caCert" .) "" }}
        - name: {{ include "mysql-exporter.fullname" . }}-redis-ca
          secret:
            secretName: "{{ include "wandb.redis.passwordSecret" . }}"
            items:
              - key: REDIS_CA_CERT
                path: redis_ca.pem
        {{- end }}
{{- end }}
