apiVersion: v2
name: lumen
description: A Helm chart for deploying the W&B Lumen processor and notebook
type: application
version: 0.2.0
appVersion: 1.0.0

maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com

dependencies:
  - name: wandb-base
    alias: lumenProcessor
    version: "0.12.3"
    repository: file://../wandb-base
  - name: wandb-base
    alias: lumenNotebook
    version: "0.12.3"
    repository: file://../wandb-base
