apiVersion: v2
name: lumen
description: A Helm chart for deploying the W&B Lumen agent
type: application
version: 0.1.1
appVersion: 1.0.0

maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com

dependencies:
  - name: wandb-base
    alias: lumen
    version: "0.11.12"
    repository: file://../wandb-base
  - name: wandb-base
    alias: notebook
    version: "0.11.12"
    repository: file://../wandb-base
