# This file is auto-generated by snapshots.sh generate-env-tests
# Do not edit manually - regenerate with: ./snapshots.sh generate-env-tests
{{- $chartRaw := file.Read (getenv "CHART_FILE") -}}
{{- $valuesRaw := file.Read (getenv "VALUES_FILE") -}}
{{- $chart := data.YAML $chartRaw -}}
{{- $values := data.YAML $valuesRaw -}}
{{- $testImage := "busybox:stable-musl" -}}
{{- $testImagePullPolicy := "IfNotPresent" }}

apiVersion: v1
kind: Pod
metadata:
  name: "{{"{{"}} include "wandb.fullname" . {{"}}"}}-test-env-expansion"
  labels:
    {{"{{"}}- include "wandb.labels" . | nindent 4 {{"}}"}}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: env-expansion-test-anchor
      image: {{ $testImage }}
      imagePullPolicy: {{ $testImagePullPolicy }}
      command: &env-expansion-test-command
        - sh
        - -c
        - |
          echo "Checking for unresolved \$(VARIABLE) references in environment..."
          echo ""
          
          # Check for $(VARIABLE) style references
          FOUND=$(env | grep '(' || true)
          
          if [ -n "$FOUND" ]; then
            echo "ERROR: Found \$(VARIABLE) references in environment:"
            echo "$FOUND"
            echo ""
            echo "This typically indicates one of two issues:"
            echo "1. ConfigMap values using \$(VAR) instead of Helm templating"
            echo "2. Environment variables referencing \$(VAR) that aren't set in the pod"
            echo ""
            echo "For ConfigMaps: Use Helm templating at template-render time."
            echo "For env vars: Ensure referenced variables are defined in a _*.tpl file"
            echo "             and included via envTpls in values.yaml."
            echo ""
            exit 1
          fi
          
          echo "SUCCESS: No unresolved \$(VARIABLE) references found."
          exit 0
{{- range $dep := $chart.dependencies -}}
{{- if and (eq $dep.name "wandb-base") $dep.alias -}}
{{- $service := $dep.alias -}}
{{- $config := index $values $service }}
{{- if $config }}
{{- $hasInstall := index $config "install" }}
{{- if ne $hasInstall nil }}
{{"{{"}}- if index .Values "{{ $service }}" "install" {{"}}"}}
{{- end }}
    - name: {{ strings.ToLower (printf "%s-env-check" $service) }}
      image: {{ $testImage }}
      imagePullPolicy: {{ $testImagePullPolicy }}
{{- $envFrom := index $config "envFrom" }}
{{- if $envFrom }}
      envFrom:
{{- range $key := coll.Sort (coll.Keys $envFrom) }}
        - {{ index $envFrom $key }}:
            name: {{"{{"}} tpl "{{ $key }}" . {{"}}"}}
            optional: true
{{- end }}
{{- end }}
      env:
{{- $envTpls := index $config "envTpls" }}
{{- if $envTpls }}
{{- range $tpl := $envTpls }}
{{ strings.ReplaceAll " }}" " | indent 8 }}" $tpl }}
{{- end }}
{{- end }}
{{- $env := index $config "env" }}
{{- if ne $env nil }}
{{"{{"}} include "wandb-base.env" (dict "env" (index .Values "{{ $service }}" "env") "root" .) | indent 8 {{"}}"}}
{{- end }}
      command: *env-expansion-test-command
{{- if ne $hasInstall nil }}
{{"{{"}}- end {{"}}"}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
  restartPolicy: Never
