{{- if .Values.enabled }}
{{- $imageCfg := dict "global" $.Values.global.image "local" $.Values.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weave.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weave.commonLabels" . | nindent 4 }}
    {{- include "weave.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels -}}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "wandb.selectorLabels" $ | nindent 6 }}
      {{- include "weave.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wandb.podLabels" . | nindent 8 }}
        {{- include "weave.commonLabels" . | nindent 8 }}
        {{- include "weave.podLabels" . | nindent 8 }}
        {{- include "weave.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- include "wandb.nodeSelector" . | nindent 6 }}
      {{- include "wandb.priorityClassName" . | nindent 6 }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "weave.fullname" .  }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- include "wandb.containerSecurityContext" .Values.container.securityContext | nindent 10 }}
          ports:
            - name: http
              containerPort: 9994
              protocol: TCP
          env:
            {{ include "wandb.license" . | nindent 12 }}
            - name: ONLY_SERVICE
              value: weave
            - name: WANDB_PUBLIC_BASE_URL
              value: {{ .Values.global.host }}
            - name: WEAVE_LOG_FORMAT
              value: json
            - name: WEAVE_LOCAL_ARTIFACT_DIR
              value: /vol/weave/cache
            - name: WANDB_BASE_URL
              value: http://{{ .Release.Name }}-app:8080/
            - name: WEAVE_SERVER_NUM_WORKERS
              value: "4"
            - name: GORILLA_TSHIRT_SIZE
              value: {{ .Values.global.size | quote }}

            {{- include "weave.extraEnv" (dict "global" .Values.global "local" .Values) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}
          envFrom:
          {{- if .Values.envFrom }}
            {{- tpl (include "weave.envFrom" . ) . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /__weave/hello
              port: http
          readinessProbe:
            httpGet:
              path: /__weave/hello
              port: http
          startupProbe:
            httpGet:
              path: /__weave/hello
              port: http
            failureThreshold: 12
            periodSeconds: 10

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: cache
              mountPath: /vol/weave/cache

        - name: {{ include "weave.fullname" . }}-cache-clear
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- include "wandb.containerSecurityContext" .Values.container.securityContext | nindent 10 }}
          command:
            - /bin/bash
            - -c
            - |
              if [ -f /var/app/weave-python/venv/bin/activate ]; then
                source /var/app/weave-python/venv/bin/activate
              fi
              python -m weave.clear_cache
          env:
            {{ include "wandb.license" . | nindent 12 }}
            - name: WEAVE_LOCAL_ARTIFACT_DIR
              value: /vol/weave/cache
            - name: WEAVE_CACHE_CLEAR_INTERVAL
              value: "{{ .Values.cache.intervalInHours }}"

            {{- include "weave.extraEnv" (dict "global" .Values.global "local" .Values) | nindent 12 }}
            {{- include "wandb.extraEnvFrom" (dict "root" $ "local" .) | nindent 12 }}

          volumeMounts:
            - name: cache
              mountPath: /vol/weave/cache

          resources:
            {{- toYaml .Values.cacheClear.resources | nindent 12 }}
      serviceAccountName: {{ include "weave.serviceAccountName" . }}
      volumes:
        - name: cache
          emptyDir: 
            sizeLimit: {{ .Values.cache.size }}
            medium: {{ .Values.cache.medium }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name:  {{ include "weave.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "weave.commonLabels" . | nindent 4 }}
    {{- include "weave.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "weave.fullname" . }}
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
