{{- if eq (include "clickhouse.shouldInstall" .) "true" }}
{{- if and (not .Values.bucket.useInstanceMetadata) (not .Values.bucket.accessKeyId) (not .Values.bucket.secretAccessKey) }}
{{- $secretName := .Values.bucket.secret.secretName -}}
{{- if $secretName -}}
{{- $secretExists := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secretExists }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
type: Opaque
data:
  # Empty defaults for keys - you should replace these with actual credentials
  {{ .Values.bucket.secret.accessKeyName }}: {{ randAlphaNum 8 | b64enc }}
  {{ .Values.bucket.secret.secretKeyName }}: {{ randAlphaNum 20 | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }} 
