{{- if eq (include "clickhouse.shouldInstall" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-ch-server
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.server.tcpPort }}
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: {{ .Values.server.intrsrvhttpPort }}
      targetPort: intrsrvhttp
      protocol: TCP
      name: intrsrvhttp
  selector:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-ch-server-headless
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.server.tcpPort }}
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: {{ .Values.server.intrsrvhttpPort }}
      targetPort: intrsrvhttp
      protocol: TCP
      name: intrsrvhttp
  selector:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  publishNotReadyAddresses: true
{{- end }}
