{{- if .Values.install }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clickhouse.fullname" . }}-ch-server
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "clickhouse.commonLabels" . | nindent 4 }}
    {{- include "clickhouse.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels }}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ include "clickhouse.replicas" . }}
  podManagementPolicy: "{{ .Values.common.podManagementPolicy }}"
  selector:
    matchLabels:
      {{ include "wandb.selectorLabels" $ | nindent 6 }}
      {{ include "clickhouse.labels" . | nindent 6 }}
  serviceName: {{ include "clickhouse.fullname" . }}-ch-server-headless
  template:
    metadata:
      labels:
        {{ include "wandb.podLabels" . | nindent 8 }}
        {{ include "clickhouse.commonLabels" . | nindent 8 }}
        {{ include "clickhouse.podLabels" . | nindent 8 }}
        {{ include "clickhouse.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
      {{- include "wandb.imagePullSecrets" . }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: clickhouse
          image: "{{ .Values.server_image.repository }}:{{ .Values.server_image.tag }}"
          {{- include "wandb.containerSecurityContext" .Values.container.securityContext | nindent 10 }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wandb.clickhouse.passwordSecret" . }}
                  key: {{ include "wandb.clickhouse.passwordSecret.passwordKey" . }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/clickhouse-server/config.xml
              subPathExpr: "$(POD_NAME).xml"
              readOnly: true
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
              readOnly: false
            - name: clickhouse-log
              mountPath: /var/log/clickhouse-server
              readOnly: false
          resources:
            limits:
              cpu: {{ .Values.server.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.server.resources.limits.ephemeralStorage }}
              memory: {{ .Values.server.resources.limits.memory }}
            requests:
              cpu: {{ .Values.server.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.server.resources.requests.ephemeralStorage }}
              memory: {{ .Values.server.resources.requests.memory }}
          ports:
            - name: http
              containerPort: {{ include "wandb.clickhouse.port" . }}
            - name: tcp
              containerPort: {{ .Values.server.tcpPort }}
            - name: intrsrvhttp
              containerPort: {{ .Values.server.intrsrvhttpPort }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            tcpSocket:
              port: http
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /ping
              port: http
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "clickhouse.fullname" . }}-ch-server-config
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-pvc  # PVC for persistent data
        - name: clickhouse-log
          emptyDir: {}  # Or use a PVC if logs need persistence

  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
{{- end }}
