{{- if .Values.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}-ch-server-config
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
{{- include "clickhouse.serverConfig" . | trim | nindent 2 }}
{{- end }}
