{{- if eq (include "clickhouse.shouldInstall" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}-ch-keeper-config
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  {{- include "clickhouse.keeperConfig" . | nindent 2 }}
{{- end }}
