{{- if .Values.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wandb.fullname" . }}-ch-keeper-config
  labels:
    {{- include "wandb.labels" . | nindent 4 }}
data:
  {{- include "clickhouse.keeperConfig" . | nindent 2 }}
{{- end }}
