{{- if .Values.install }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clickhouse.fullname" . }}-ch-keeper
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "clickhouse.commonLabels" . | nindent 4 }}
    {{- include "clickhouse.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels }}
    {{-   toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "wandb.deploymentAnnotations" $ | nindent 4 }}
    {{- if .Values.deployment.annotations -}}
    {{-   toYaml .Values.deployment.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ include "clickhouse.keeper.replicas" . }}
  podManagementPolicy: "{{ .Values.common.podManagementPolicy }}"
  selector:
    matchLabels:
      {{ include "wandb.selectorLabels" $ | nindent 6 }}
      {{ include "clickhouse.labels" . | nindent 6 }}
  serviceName: {{ include "clickhouse.fullname" . }}-ch-keeper-headless
  template:
    metadata:
      labels:
        {{ include "wandb.podLabels" . | nindent 8 }}
        {{ include "clickhouse.commonLabels" . | nindent 8 }}
        {{ include "clickhouse.podLabels" . | nindent 8 }}
        {{ include "clickhouse.labels" . | nindent 8 }}
      annotations:
        {{- if .Values.pod.annotations -}}
        {{-   toYaml .Values.pod.annotations | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
      {{- include "wandb.imagePullSecrets" . }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- include "wandb.podSecurityContext" .Values.pod.securityContext | nindent 6 }}
      containers:
        - name: keeper
          image: "{{ .Values.keeper_image.repository }}:{{ .Values.keeper_image.tag }}"
          {{- include "wandb.containerSecurityContext" .Values.container.securityContext | nindent 10 }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLICKHOUSE_USER
              value: "default"
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wandb.clickhouse.passwordSecret" . }}
                  key: CLICKHOUSE_PASSWORD
          volumeMounts:
            - name: processed-config
              mountPath: /etc/clickhouse-keeper
            - name: keeper-data
              mountPath: /var/lib/clickhouse
            - name: keeper-data
              mountPath: /var/lib/clickhouse-keeper
            - name: keeper-data
              mountPath: /var/log/clickhouse-keeper
            - name: config-volume
              mountPath: /etc/clickhouse-keeper/keeper_config.xml
              subPathExpr: "$(POD_NAME).xml"
              readOnly: true
          resources:
            limits:
              cpu: {{ .Values.keeper.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.keeper.resources.limits.ephemeralStorage }}
              memory: {{ .Values.keeper.resources.limits.memory }}
            requests:
              cpu: {{ .Values.keeper.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.keeper.resources.requests.ephemeralStorage }}
              memory: {{ .Values.keeper.resources.requests.memory }}
          ports:
            - name: tcp
              containerPort: {{ .Values.keeper.tcpPort }}
            - name: raft
              containerPort: {{ .Values.keeper.raftPort }}
            - name: http
              containerPort: {{ .Values.keeper.httpPort }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /ready
              port: http
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /ready
              port: http
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "clickhouse.fullname" . }}-ch-keeper-config
        - name: processed-config
          emptyDir: {}
        - name: keeper-logs
          emptyDir: {} 

  volumeClaimTemplates:
    - metadata:
        name: keeper-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
{{- end }}
