{{- if eq (include "clickhouse.shouldInstall" .) "true" }}
{{- $secretName := include "clickhouse.local.passwordSecret" . -}}
{{- $secretExists := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secretExists }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "clickhouse.local.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- $password := include "clickhouse.local.password" . | b64enc }}
  CLICKHOUSE_PASSWORD: {{ $password }}
{{- end }}
{{- end }} 
