{{- if eq (include "clickhouse.shouldInstall" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.local.passwordSecret" . }}
  labels:
    {{- include "clickhouse.local.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- $password := include "clickhouse.local.password" . | b64enc }}
  CLICKHOUSE_PASSWORD: {{ $password }}
{{- end }} 
