{{- if .Values.install }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "wandb.fullname" . }}-keeper-config
    labels:
        {{- include "wandb.labels" . | nindent 4 }}
data:
  ch-keeper-0.xml: |
    <clickhouse replace="true">
        <path>/var/lib/clickhouse/coordination/keeper</path>
        <logger>
            <level>information</level>
            <console>true</console>
            <log remove="remove"/>
            <errorlog remove="remove"/>
            <!-- log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
            <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
            <size>1000M</size>
            <count>3</count -->
        </logger>
        <listen_host>0.0.0.0</listen_host>
        <keeper_server>
            <tcp_port>{{ .Values.container.keeper.configmap.tcpPort }}</tcp_port>
            <http_control>
              <port>{{ .Values.container.keeper.configmap.httpPort }}</port>
              <readiness><endpoint>/ready</endpoint></readiness>
            </http_control>
            <server_id>0</server_id>
            <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
            <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
            <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <session_timeout_ms>30000</session_timeout_ms>
                <raft_logs_level>information</raft_logs_level>
            </coordination_settings>
            <raft_configuration>
            {{- range $index, $replica := .Values.container.keeper.configmap.replicas }}
                <server>
                <id>{{ $index }}</id>
                <host>{{ $replica.host }}</host>
                <port>{{ $replica.port }}</port>
                </server>
            {{- end }}
            </raft_configuration>
        </keeper_server>
    </clickhouse>
  ch-keeper-1.xml: |
    <clickhouse replace="true">
        <path>/var/lib/clickhouse/coordination/keeper</path>
        <logger>
            <level>information</level>
            <console>true</console>
            <log remove="remove"/>
            <errorlog remove="remove"/>
            <!-- log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
            <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
            <size>1000M</size>
            <count>3</count -->
        </logger>
        <listen_host>0.0.0.0</listen_host>
        <keeper_server>
            <tcp_port>{{ .Values.container.keeper.configmap.tcpPort }}</tcp_port>
            <http_control>
              <port>{{ .Values.container.keeper.configmap.httpPort }}</port>
              <readiness><endpoint>/ready</endpoint></readiness>
            </http_control>
            <server_id>1</server_id>
            <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
            <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
            <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <session_timeout_ms>30000</session_timeout_ms>
                <raft_logs_level>information</raft_logs_level>
            </coordination_settings>
            <raft_configuration>
            {{- range $index, $replica := .Values.container.keeper.configmap.replicas }}
                <server>
                <id>{{ $index }}</id>
                <host>{{ $replica.host }}</host>
                <port>{{ $replica.port }}</port>
                </server>
            {{- end }}
            </raft_configuration>
        </keeper_server>
    </clickhouse>
  ch-keeper-2.xml: |
    <clickhouse replace="true">
        <path>/var/lib/clickhouse/coordination/keeper</path>
        <logger>
            <level>information</level>
            <console>true</console>
            <log remove="remove"/>
            <errorlog remove="remove"/>
            <!-- log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
            <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
            <size>1000M</size>
            <count>3</count -->
        </logger>
        <listen_host>0.0.0.0</listen_host>
        <keeper_server>
            <tcp_port>{{ .Values.container.keeper.configmap.tcpPort }}</tcp_port>
            <http_control>
              <port>{{ .Values.container.keeper.configmap.httpPort }}</port>
              <readiness><endpoint>/ready</endpoint></readiness>
            </http_control>
            <server_id>2</server_id>
            <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
            <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
            <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <session_timeout_ms>30000</session_timeout_ms>
                <raft_logs_level>information</raft_logs_level>
            </coordination_settings>
            <raft_configuration>
            {{- range $index, $replica := .Values.container.keeper.configmap.replicas }}
                <server>
                <id>{{ $index }}</id>
                <host>{{ $replica.host }}</host>
                <port>{{ $replica.port }}</port>
                </server>
            {{- end }}
            </raft_configuration>
        </keeper_server>
    </clickhouse>
{{- end }}