apiVersion: v1
kind: Service
metadata:
  name: {{ include "parquet.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "parquet.labels" . | nindent 4 }}
    {{- include "parquet.commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8087
      protocol: TCP
      name: parquet
  selector:
    app.kubernetes.io/component: "service"
    {{- include "parquet.labels" . | nindent 4 }}
