_wandb:
    value:
        cli_version: 0.21.1
        e:
            z9zh3tq8tief7p7wisiboht4te3tfync:
                args:
                    - verify
                email: peyton.sarmiento@wandb.com
                executable: /Users/peytonsarmiento/.pyenv/versions/3.11.6/bin/python3.11
                host: Peyton-Sarmiento-H4QDYT9T4Y
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/peytonsarmiento/.pyenv/versions/3.11.6/bin/wandb
                python: CPython 3.11.6
                root: /Users/peytonsarmiento/helm-charts
                startedAt: "2025-08-22T20:55:47.102460Z"
                writerId: z9zh3tq8tief7p7wisiboht4te3tfync
        m: []
        python_version: 3.11.6
        t:
            "3":
                - 2
                - 3
                - 14
                - 16
                - 61
            "4": 3.11.6
            "5": 0.21.1
            "10":
                - 20
            "12": 0.21.1
            "13": darwin-arm64
dictTest:
    value:
        config_string: config string
        config_val: 2
epochs:
    value: 4
listTest:
    value:
        - 0
        - one
        - "2"
stringTest:
    value: A test config
