containers:
  pubsub-emulator:
    image:
      repository: "gcr.io/google.com/cloudsdktool/google-cloud-cli"
      tag: "520.0.0-emulators"
    args:
      - "gcloud"
      - "beta"
      - "emulators"
      - "pubsub"
      - "start"
      - "--host-port=0.0.0.0:8085"
      - "--project=playground-111"
    ports:
      - containerPort: 8085
        name: pubsub
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 2Gi
        cpu: 1
podSecurityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false
  runAsUser: 0
service:
  enabled: true
  ports:
    - port: 8085
      targetPort: pubsub
      name: pubsub