mode: "daemonset"

nameOverride: ""
fullnameOverride: ""

config: {}
presets:
  receivers:
    hostMetrics: false
    logsCollection: false
    kubeletMetrics: false
    kubernetesEvent: false
    kubernetesCluster: false
    statsd: true
    otlp: true

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.97.0
  pullPolicy: IfNotPresent
  # pullSecrets: []

# Tolerations for pod scheduling
tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []

service: {}

pod:
  labels: {}
  annotations: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 0
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
    seccompProfile:
      type: ""

container:
  securityContext:
    capabilities:
      add: []
      drop: []
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    privileged: false

clusterRole:
  annotations: {}
  labels: {}

common:
  labels: {}
  annotations: {}

daemonSet:
  labels: {}
  annotations: {}

deployment:
  labels: {}
  annotations: {}

configMap:
  annotations: {}
  labels: {}

resources:
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 1000m
    memory: 1000Mi

serviceAccount:
  create: true

role: {}
roleBinding: {}
