{{- $bucket := include "wandb.lumen.dataRoot" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  LUMEN_DATA_ROOT: {{ $bucket | quote }}
  LUMEN_STAGING_ROOT: "file://{{ include "wandb.lumen.stagingPath" . }}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-marimo-configmap
data:
  XDG_CONFIG_HOME: "{{ include "wandb.lumen.stagingPath" . }}/.config"
  XDG_STATE_HOME: "{{ include "wandb.lumen.stagingPath" . }}/.local/state"
  XDG_CACHE_HOME: "{{ include "wandb.lumen.stagingPath" . }}/.cache"