apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-lumen-configmap
data:
  LUMEN_CONFIG_PATH: "/app/definitions/collector/managed-install.yaml"
  LUMEN_SNAPSHOT_PREFIX: "{{ .Values.config.snapshotPrefix | default "snapshot" }}"
  LUMEN_CUSTOMER_NAME: "{{ .Release.Name }}"
  LUMEN_DATA_ROOT: {{ required "config.lumenDataRoot is required" .Values.config.lumenDataRoot | quote }}
