{{- if and .Values.ui.enabled .Values.ui.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-ui
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: {{ required "ui.secretProviderClass.sessionSecretResourceName is required" .Values.ui.secretProviderClass.sessionSecretResourceName | quote }}
        path: "session-secret"
      - resourceName: {{ required "ui.secretProviderClass.githubClientSecretResourceName is required" .Values.ui.secretProviderClass.githubClientSecretResourceName | quote }}
        path: "github-client-secret"
{{- end }}
