nameOverride: ""
fullnameOverride: ""

image:
  repository: wandb/weave-trace
  tag: latest
  pullPolicy: Always

tolerations: []

extraEnv: {}
extraEnvFrom: {}

extraCors: []

common:
  labels: {}
deployment: {}
serviceAccount:
  create: true
  annotations: {}
clusterRole: {}

service:
  type: ClusterIP
  annotations: {}

pod:
  labels: {}
  annotations: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 0
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
    seccompProfile:
      type: ""

container:
  securityContext:
    capabilities:
      add: []
      drop: []
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    privileged: false

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 6Gi

datadog:
  enabled: false
  service: "weave-trace"
  env: "managed-install"
  traceEnabled: false
  logsEnabled: false
  logsInjection: false

migration:
  # By default, use the init container method to migrate clickhouse
  # Otherwise, use the helm pre-upgrade hook (may not work for install)
  useHook: false
