apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-registry-search
data:
  host: "clickhouse.example.com"
  port: "9440"
  user: "default"
  database: "registry_search"
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-registry-search-password
type: Opaque
stringData:
  password: "registry-search-password-123"
