---
testsuite:
  name: "with minimal redis"
  expected:
    redis:
      host: my-redis-host
      port: 6377
      password: ""
      connectString: "redis://$(REDIS_HOST):$(REDIS_PORT)"
global:
  redis:
    host: my-redis-host
    port: 6377
redis:
  install: false
---
testsuite:
  name: "with redis password"
  expected:
    redis:
      host: my-redis-host
      port: 6377
      password: ""
      connectString: "redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)"
global:
  redis:
    host: my-redis-host
    port: 6377
    password: my-redis-password
redis:
  install: false
---

