dynamicFields:
  - jsonPath:
    - /metadata/labels/helm.sh~1chart
    value: '###CHART_VERSION###'
  - apiVersion: v1
    kind: Deployment
    jsonPath:
      - /spec/template/metadata/labels/helm.sh~1chart
  - apiVersion: v1
    kind: Secret
    name: chartsnap-gorilla-session-key
    jsonPath:
      - /data/GORILLA_SESSION_KEY
  - apiVersion: v1
    kind: Secret
    name: chartsnap-mysql
    jsonPath:
      - /data/MYSQL_ROOT_PASSWORD
      - /data/MYSQL_PASSWORD
  - apiVersion: v1
    kind: Secret
    name: chartsnap-clickhouse
    jsonPath:
      - /data/CLICKHOUSE_PASSWORD
