global:
  bucket:
    provider: "s3"
    name: "minio.minio.svc.cluster.local:9000/bucket"
    region: "us-east-1"
    accessKey: "minio"
    secretKey: "testpassword"
  env:
    GLOBAL_ADMIN_API_KEY: "local-123456789-123456789-123456789-1234"
    GORILLA_INSECURE_ALLOW_API_KEY_ADMIN_ACCESS: "true"
  size: "testing"
  common:
    labels:
      global-common-label: "global-common-label-value"
    annotations:
      global-common-annotation: "global-common-annotation-value"
  deployment:
    labels:
      global-deployment-label: "global-deployment-label-value"
    annotations:
      global-deployment-annotation: "global-deployment-annotation-value"
  pod:
    labels:
      global-pod-label: "global-pod-label-value"
    annotations:
      global-pod-annotation: "global-pod-annotation-value"

app:
  common:
    labels:
      app-common-label: "app-common-label-value"
    annotations:
      app-common-annotation: "app-common-annotation-value"
  deployment:
    labels:
      app-deployment-label: "app-deployment-label-value"
    annotations:
      app-deployment-annotation: "app-deployment-annotation-value"
  pod:
    labels:
      app-pod-label: "app-pod-label-value"
    annotations:
      app-pod-annotation: "app-pod-annotation-value"
  env:
    GORILLA_STORAGE_BUCKET: "s3://local-files"

console:
  containers:
    console:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi

ingress:
  install: false
  create: false

mysql:
  install: true
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"

redis:
  install: true
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"

reloader:
  install: true
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"

anaconda2:
  install: true
