global:
  bucket:
    provider: "s3"
    name: "minio.minio.svc.cluster.local:9000/bucket"
    region: "us-east-1"
    accessKey: "minio"
    secretKey: "testpassword"
  env:
    GLOBAL_ADMIN_API_KEY: "local-123456789-123456789-123456789-1234"
    GORILLA_INSECURE_ALLOW_API_KEY_ADMIN_ACCESS: "true"
  size: "testing"

app:
  env:
    GORILLA_STORAGE_BUCKET: "s3://local-files"

console:
  containers:
    console:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi

ingress:
  install: false
  create: false

mysql:
  install: true
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"

redis:
  install: true
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"

reloader:
  install: true
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
