global:
  auth:
    oidc:
      clientId: "myclientid"
      authMethod: "oidc"
      issuer: "myissuer"
      secret: "mysecret"
  api:
    enabled: true
app:
  extraCors:
    - "https://example.com"
    - "https://another.example.com"