global:
  host: https://customer.example.com
  cloudProvider: azure
  traefikIngress: true
  api:
    enabled: true
  ipAllowList:
    enabled: true
    userCIDRs: [192.0.2.0/24]
ingress:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: cert-issuer
  tls:
    - hosts: [customer.example.com]
      secretName: wandb-ssl-cert
mcp-server:
  install: true
weave-trace:
  install: true
