enabled: true

nameOverride: ""
fullnameOverride: ""

proxy:
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
  debug: false

image:
  repository: wandb/console
  tag: latest
  pullPolicy: Always
  # pullSecrets: []

hostNetwork: false

# Tolerations for pod scheduling
tolerations: []

extraEnv:
  BUCKET_ACCESS_IDENTITY: unknown
  TESTING: true
extraEnvFrom: {}

extraCors: []

common:
  labels: {}
deployment: {}
serviceAccount:
  create: true
  annotations: {}

clusterRole:
  enabled: true

pod:
  labels: {}
  annotations: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 0
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
    seccompProfile:
      type: ""

container:
  securityContext:
    capabilities:
      add: []
      drop: []
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    privileged: false

service:
  type: ClusterIP
  annotations: {}
  labels: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a
  # conscious choice for the user. This also increases chances charts run on
  # environments with little resources, such as Minikube. If you do want to
  # specify resources, uncomment the following lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 1
    memory: 500Mi
