nameOverride: ""
fullnameOverride: ""

replicas: 3

server_image:
  repository: "clickhouse/clickhouse-server"
  tag: "24.8"

keeper_image:
  repository: "clickhouse/clickhouse-keeper"
  tag: "24.8"

database: "weave_trace_db"

server:
  tcpPort: 9000
  intrsrvhttpPort: 9009
  zookeeperPort: 9181
  cluster: "wandb_cluster"
  resources:
    limits:
      cpu: 6
      memory: 2048Mi
    requests:
      cpu: "1"
      ephemeralStorage: 10Gi
      memory: 2048Mi

keeper:
  tcpPort: 9181
  httpPort: 9182
  raftPort: 9234
  resources:
    limits:
      cpu: "1.5"
      ephemeralStorage: 20Gi
      memory: 4096Mi
    requests:
      cpu: "0.5"
      ephemeralStorage: 500Mi
      memory: 1024Mi

cache:
  size: 20Gi
  path: /var/lib/clickhouse/cache

service:
  annotations: {}
  labels: {}

common:
  annotations: {}
  labels: {}

deployment:
  labels: {}
  annotations: {}

pod:
  labels: {}
  annotations: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 0
    fsGroup: 999
    fsGroupChangePolicy: "OnRootMismatch"
    seccompProfile:
      type: ""

container:
  securityContext:
    capabilities:
      add: []
      drop: []
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    privileged: false

logLevel: information

# Node selector for the StatefulSet pods (for scheduling pods on specific nodes)
nodeSelector: {}

# Tolerations for the StatefulSet pods (for allowing pods to be scheduled on tainted nodes)
tolerations: []

# Affinity settings for the StatefulSet pods (for custom scheduling rules)
affinity: {}

# Persistent volume claim settings for the StatefulSet
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

serviceAccount:
  name: "clickhouse"
  automountServiceAccountToken: false
  create: true
  annotations: {}

bucket:
  secret:
    secretName: ""
    accessKeyName: "ACCESS_KEY"
    secretKeyName: "SECRET_KEY"
  region: ""  # Required: AWS region for S3 buckets (e.g., us-east-1, eu-central-1)
  endpoints:  # Required: List of S3 bucket names for each replica
    - ""
    - ""
    - ""
