nameOverride: ""
fullnameOverride: ""

replicas: 3

server_image:
  repository: "clickhouse/clickhouse-server"
  tag: "24.8"

keeper_image:
  repository: "clickhouse/clickhouse-keeper"
  tag: "24.8"

database: "weave_trace_db"

server:
  tcpPort: 9000
  intrsrvhttpPort: 9009
  zookeeperPort: 9181
  cluster: "wandb_cluster"
  resources:
    limits:
      cpu: 6
      memory: 2048Mi
    requests:
      cpu: "1"
      ephemeralStorage: 10Gi
      memory: 2048Mi

keeper:
  tcpPort: 9181
  httpPort: 9182
  raftPort: 9234
  resources:
    limits:
      cpu: "1.5"
      ephemeralStorage: 20Gi
      memory: 4096Mi
    requests:
      cpu: "0.5"
      ephemeralStorage: 500Mi
      memory: 1024Mi

service:
  annotations: {}
  labels: {}
    
common:
  labels: {}
  podManagementPolicy: "Parallel"
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: false
    seLinuxOptions:
      level: "s0:c27,c4"
    seccompProfile:
      type: RuntimeDefault

deployment:
  labels: {}
  annotations: {}

pod:
  labels: {}
  annotations: {}

logLevel: information

# Node selector for the StatefulSet pods (for scheduling pods on specific nodes)
nodeSelector: {}

# Tolerations for the StatefulSet pods (for allowing pods to be scheduled on tainted nodes)
tolerations: []

# Affinity settings for the StatefulSet pods (for custom scheduling rules)
affinity: {}

# Persistent volume claim settings for the StatefulSet
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

serviceAccount:
  name: "clickhouse"
  automountServiceAccountToken: false
  create: true
  annotations: {}

localStorage: "100Gi"

buckets:
  # Access credentials should be provided via secret in production
  # Example: kubectl create secret generic clickhouse-s3-credentials --from-literal=access_key_id=your-key --from-literal=secret_access_key=your-secret
  secret:
    name: ""  # Name of the secret containing S3 credentials
    accessKeyKey: "ACCESS_KEY_ID"  # Key in the secret containing the access key
    secretKeyKey: "SECRET_ACCESS_KEY"  # Key in the secret containing the secret key
  region: ""  # Required: AWS region for S3 buckets (e.g., us-east-1, eu-central-1)
  replicaBucketNames: []  # Required: List of S3 bucket names for each replica
