daemonset:
  install: true
  mode: "daemonset"
  presets:
    receivers:
      hostMetrics: true
      logsCollection: true
      kubeletMetrics: true
      kubernetesEvent: true
      kubernetesCluster: true
      statsd: true
      otlp: true
      prometheusSelf: true
  config:
    service:
      pipelines:
        traces:
          exporters: [debug]
          # memory_limiter should be the first processor in the pipeline: https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md
          processors: [memory_limiter, batch, k8sattributes]
          receivers: [otlp]
        metrics:
          exporters: [debug, prometheus]
          processors: [memory_limiter, batch, k8sattributes]
          receivers: [hostmetrics, k8s_cluster, kubeletstats, prometheus_self]
        logs:
          exporters: [debug]
          processors: [memory_limiter, batch, k8sattributes]
          receivers: [filelog]

deployment:
  install: true
  mode: "deployment"
  presets:
    receivers:
      statsd: true
      otlp: true
  config:
    service:
      pipelines:
        traces:
          exporters: [debug]
          processors: [memory_limiter, batch, k8sattributes]
          receivers: [otlp]
        metrics:
          exporters: [debug, prometheus]
          processors: [memory_limiter, batch, k8sattributes]
          receivers: [otlp]
        logs:
          exporters: [debug]
          processors: [memory_limiter, batch, k8sattributes]
          receivers: [otlp]
