dynamicFields:
  - jsonPath:
    - /metadata/labels/helm.sh~1chart
    value: '###CHART_VERSION###'
  - kind: Job
    jsonPath:
      - /spec/template/metadata/labels/helm.sh~1chart
    value: "###CHART_VERSION###"
  - kind: Deployment
    jsonPath:
      - /spec/template/metadata/labels/helm.sh~1chart
    value: "###CHART_VERSION###"