global:
  volumes:
    - name: shared-config
      configMap:
        name: shared-config
  volumeMounts:
    - name: shared-config
      mountPath: /config/

kind: Job
jobs:
  test:
    volumes:
      - name: shared-config
        emptyDir: {}
    initContainers:
      start:
        image:
          repository: debian
          tag: 12-slim
        command:
          - /bin/bash
        args:
          - -c
          - |
            ls -hal /config/
    containers:
      test:
        image:
          repository: debian
          tag: 12-slim
        command:
          - /bin/bash
        args:
          - -c
          - |
            ls -hal /config/
