global:
  volumes:
    - name: shared-config
      emptyDir: {}
  volumeMounts:
    - name: shared-config
      mountPath: /config/

kind: Job
jobs:
  test:
    initContainers:
      start:
        image:
          repository: debian
          tag: 12-slim
        command:
          - /bin/bash
        args:
          - -c
          - |
            ls -hal /config/
    containers:
      test:
        image:
          repository: debian
          tag: 12-slim
        command:
          - /bin/bash
        args:
          - -c
          - |
            ls -hal /test/
        volumeMounts:
          - name: shared-config
            mountPath: /test/
