{{- range $cronJobName, $cronJob := .Values.cronJobs }}
  {{- $_ := set $cronJob "restartPolicy" (default "Never" $cronJob.restartPolicy) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" $.Release.Name $cronJobName }}
  labels:
    {{- include "wandb-base.labels" $ | nindent 4 }}
spec:
  concurrencyPolicy: "{{ $cronJob.concurrencyPolicy }}"
  schedule: "{{ $cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        {{- include "wandb-base.pod" (dict "podData" $cronJob "root" $) | nindent 8 }}
---
{{- end }}