{{- if eq .Values.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wandb-base.fullname" . }}{{ include "wandb-base.deploymentPostfix" . }}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
  {{- if (or .Values.addReloaderAnnotations (include "wandb-base.deploymentAnnotations" .)) }}
  annotations:
    {{- if .Values.addReloaderAnnotations }}
    reloader.stakater.com/auto: "true"
    {{- end }}
    {{- tpl (include "wandb-base.deploymentAnnotations" . | nindent 4) . }}
  {{- end }}
spec:
  replicas: {{ include "wandb-base.replicaCount" . }}
  strategy:
    {{ include "wandb-base.deploymentRolloutStrategy" . | nindent 4 }}
  selector:
    matchLabels:
      {{- include "wandb-base.selectorLabels" . | nindent 6 }}
  template:
    {{- include "wandb-base.pod" (dict "podData" $.Values "root" $) | nindent 4 }}
{{- end }}
