{{- if eq .Values.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wandb-base.fullname" . }}{{ include "wandb-base.deploymentPostfix" . }}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
  {{- if .Values.addReloaderAnnotations }}
  annotations:
    {{- tpl (include "wandb-base.reloaderannotations" . | nindent 4) . }}
    {{- tpl (include "wandb-base.deploymentAnnotations" . | nindent 4) . }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wandb-base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.podAnnotationsTpls }}
      annotations:
        {{- range .Values.podAnnotationsTpls }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
        {{- tpl (toYaml .Values.podAnnotations | nindent 8) . }}
        {{- tpl (include "wandb-base.podAnnotations" | nindent 8) . }}
      {{- end }}
      labels:
        {{- tpl (include "wandb-base.labels" . | nindent 8) . }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml . | nindent 8) $ }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml . | nindent 8) $ }}
      {{- end }}
      serviceAccountName: {{ include "wandb-base.serviceAccountName" . }}
      securityContext:
       {{- tpl (toYaml .Values.podSecurityContext | nindent 8) . }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- include "wandb-base.containers" (dict "containers" .Values.initContainers "root" . "source" "initContainers") | nindent 8 }}
      {{- end }}
      containers:
        {{- include "wandb-base.containers" (dict "containers" .Values.containers "root" . "source" "containers") | nindent 8 }}
      {{- if or .Values.volumes .Values.volumesTpls  }}
      volumes:
        {{- range .Values.volumesTpls }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
        {{- if .Values.volumes }}
        {{- tpl (toYaml .Values.volumes | nindent 8) . }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml . | nindent 8) $ }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl (toYaml . | nindent 8) $ }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- tpl (toYaml . | nindent 8) $ }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
