{{- if eq .Values.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wandb-base.fullname" . }}{{ include "wandb-base.deploymentPostfix" . }}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
  {{- if .Values.addReloaderAnnotations }}
  annotations:
    {{- tpl (include "wandb-base.reloaderannotations" . | nindent 4) . }}
    {{- tpl (include "wandb-base.deploymentAnnotations" . | nindent 4) . }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wandb-base.selectorLabels" . | nindent 6 }}
  template:
    {{- include "wandb-base.pod" (dict "podData" $.Values "root" $) | nindent 4 }}
{{- end }}
