{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wandb-base.fullname" . }}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
  {{- if (or .Values.podDisruptionBudget.annotations (include "wandb-base.commonAnnotations" .)) }}
  annotations:
    {{- tpl (include "wandb-base.commonAnnotations" . | nindent 4) . }}
    {{- with .Values.podDisruptionBudget.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchExpressions:
      - key: batch.kubernetes.io/job-name
        operator: DoesNotExist
    matchLabels:
      {{- include "wandb-base.selectorLabels" . | nindent 6 }}
  {{- if and .Values.podDisruptionBudget.minAvailable .Values.podDisruptionBudget.maxUnavailable }}
    {{- fail "Cannot set both minAvailable and maxUnavailable in PodDisruptionBudget" }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}