{{- if .Values.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.role.type | default "Role" }}
metadata:
  name: {{ include "wandb-base.fullname" .}}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
  {{- if (or .Values.helmHook.enabled (include "wandb-base.commonAnnotations" .)) }}
  annotations:
    {{- tpl (include "wandb-base.commonAnnotations" . | nindent 4) . }}
    {{- if .Values.helmHook.enabled }}
      {{- include "wandb-base.helmHookAnnotations" . | nindent 4 }}
    {{- end }}
  {{- end }}
rules:
    {{- with .Values.role.rules }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
