{{- if .Values.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.role.type | default "Role" }}
metadata:
  name: {{ include "wandb-base.fullname" .}}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
rules:
    {{- with .Values.role.rules }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
