{{- define "wandb-base.serviceResource" -}}
{{- $root := .root -}}
{{- $service := .service -}}
{{- $serviceType := default "ClusterIP" $service.type -}}
{{- $isHeadless := default false $service.headless -}}
{{- $internal := or (default false $service.internal) $isHeadless -}}
{{- $rawServiceName := required "service.name is required" $service.name -}}
{{- $serviceName := tpl $rawServiceName $root | trunc 63 | trimSuffix "-" -}}
{{- if $service.enabled }}
{{- if and (not $internal) (eq $root.Values.global.cloudProvider "gcp") }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ $serviceName }}-backend-config
  labels:
    {{- include "wandb-base.labels" $root | nindent 4 }}
spec:
  {{- if $root.Values.global.gcpSecurityPolicy }}
  securityPolicy:
    name: {{ $root.Values.global.gcpSecurityPolicy }}
  {{- end }}
  timeoutSec: 120
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "wandb-base.labels" $root | nindent 4 }}
    {{- if $service.labels -}}
    {{- toYaml $service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- tpl (include "wandb-base.commonAnnotations" $root | nindent 4) $root }}
    {{- $allServiceAnnotations := merge (default (dict) $service.annotations) $root.Values.global.service.annotations }}
    {{- if $allServiceAnnotations }}
    {{- toYaml $allServiceAnnotations | nindent 4 }}
    {{- end }}
    {{- if and (not $internal) (eq $root.Values.global.cloudProvider "aws") $service.loadBalancerHealthCheckPath }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ $service.loadBalancerHealthCheckPath }}
    {{- end }}
    {{- if and (not $internal) (eq $root.Values.global.cloudProvider "gcp") }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ $serviceName }}-backend-config"}'
    {{- end }}
spec:
  type: {{ $serviceType }}
  {{- if $isHeadless }}
  clusterIP: None
  {{- end }}
  ports:
    {{- with $service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "wandb-base.selectorLabels" $root | nindent 4 }}
{{- end }}
{{- end }}

{{- $defaultService := deepCopy .Values.service -}}
{{- if not $defaultService.name -}}
{{- $_ := set $defaultService "name" (include "wandb-base.fullname" .) -}}
{{- end -}}
{{- include "wandb-base.serviceResource" (dict "root" . "service" $defaultService) }}
{{- range $service := .Values.services }}
{{- include "wandb-base.serviceResource" (dict "root" $ "service" $service) }}
{{- end }}
