{{- if .Values.serviceAccount.create -}}
{{- $azureIdentity := include "wandb-base.azureWorkloadIdentity" . | fromYaml -}}
{{- $serviceAccountAnnotations := deepCopy .Values.serviceAccount.annotations -}}
{{- if and $azureIdentity.enabled (not (kindIs "map" $azureIdentity.clientId)) -}}
{{- $_ := set $serviceAccountAnnotations "azure.workload.identity/client-id" $azureIdentity.clientId -}}
{{- end -}}
{{- if and $azureIdentity.enabled (not (kindIs "map" $azureIdentity.tenantId)) -}}
{{- $_ := set $serviceAccountAnnotations "azure.workload.identity/tenant-id" $azureIdentity.tenantId -}}
{{- end -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wandb-base.serviceAccountName" . }}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
  {{- if (or $serviceAccountAnnotations .Values.helmHook.enabled (include "wandb-base.commonAnnotations" .)) }}
  annotations:
    {{- tpl (include "wandb-base.commonAnnotations" . | nindent 4) . }}
    {{- if $serviceAccountAnnotations }}
      {{- toYaml $serviceAccountAnnotations | nindent 4 }}
    {{- end }}
    {{- if .Values.helmHook.enabled }}
      {{- include "wandb-base.helmHookAnnotations" . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
