{{- $sizingInfo := fromYaml (include "wandb-base.sizingInfo" .) }}
{{- $vpaSizing := merge .Values.autoscaling.vertical (default (dict) $sizingInfo.autoscaling.vertical) }}
{{- if $vpaSizing.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "wandb-base.fullname" . }}
  labels:
    {{- include "wandb-base.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: {{ .Values.kind }}
    name: {{ include "wandb-base.fullname" . }}
  updatePolicy:
    updateMode: {{ $vpaSizing.updateMode }}
  resourcePolicy:
    containerPolicies:
      {{- with $vpaSizing.containerPolicies }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
