apiVersion: v2
name: redis-exporter
type: application
description: A Helm chart for Kubernetes

version: 0.1.0
appVersion: "0.33.1"

home: https://wandb.ai
icon: https://wandb.ai/logo.svg

maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com
