apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-config
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
data:
  SLACK_SECRET: {{ default "" .Values.global.slack.secret | b64enc }}
  {{- if and (not .Values.global.licenseSecret.name) (not .Values.global.licenseSecret.key) .Values.global.license }}
  LICENSE: {{ .Values.global.license | b64enc }}
  {{- end }}
