{{- if eq .Values.global.cloudProvider "gcp" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-app-backend-config
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
spec:
  {{- if .Values.global.gcpSecurityPolicy }}
  securityPolicy:
    name: {{ .Values.global.gcpSecurityPolicy }}
  {{- end }}
  timeoutSec: 120
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "wandb.commonLabels" . | nindent 4 }}
    {{- include "app.labels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{-   toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8181'
    {{- if eq .Values.global.cloudProvider "gcp" }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ $.Release.Name }}-app-backend-config"}'
    {{- end }}
    {{- if .Values.service.annotations -}}
    {{-   toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
      name: app
    - port: 8181
      protocol: TCP
      name: prometheus
    - port: 8082
      protocol: TCP
      name: anaconda
    - port: 8083
      protocol: TCP
      name: local
  selector:
    {{- include "app.labels" . | nindent 4 }}
