apiVersion: v2
name: orchestrator
description: Orchestrator Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0

maintainers:
  - name: orchestrator
    email: support@wandb.ai
    url: https://wandb.ai

dependencies:
  - name: migrations
    version: "*.*.*"
    repository: file://charts/migrations
    condition: migrations.install
  - name: otel
    condition: otel.install
    version: "*.*.*"
    repository: "file://charts/otel"
  - alias: web
    name: wandb-base
    condition: web.install
    version: "0.12.0"
    repository: "file://../wandb-base"
  - alias: api
    name: wandb-base
    condition: api.install
    version: "0.12.0"
    repository: "file://../wandb-base"
  - alias: workspace-engine
    name: wandb-base
    condition: workspace-engine.install
    version: "0.12.0"
    repository: "file://../wandb-base"
