apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
spec:
  containers:
    - name: minio
      image: quay.io/minio/minio:latest
      env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "testpassword"
      command:
        - /bin/bash
        - -c
      args:
        - mkdir -p /data/bucket && minio server /data --console-address :9090
      ports:
        - containerPort: 9000
          name: minio
      volumeMounts:
        - mountPath: /data
          name: localvolume #
  volumes:
    - name: localvolume
      persistentVolumeClaim:
        claimName: minio
---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  labels:
#    app: minio
#  name: minio
#spec:
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteOnce
#---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio
  name: minio
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio # Change this value to match the namespace metadata.name
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      name: minio
