name: Lint Charts

on:
  # No paths filter: run on every PR and let ct + ct.yaml gate what's linted.
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    environment: Helm Charts
    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.16.3

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
        with:
          version: v3.11.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing  (lint)
        run: ct lint --config ct.yaml
