name: Test operator-wandb Chart

on:
  pull_request:
    paths:
      - charts/operator-wandb/**
      - test-configs/operator-wandb/**

jobs:
  snapshots:
    name: Snapshot testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0
      - name: Helm dep build
        run: |
          pushd ./charts/operator-wandb/
          helm dependency build
          popd
      - name: Chart Snapshots
        uses: jlandowner/helm-chartsnap-action@v1
        id: chartsnap
        with:
          chart:  charts/operator-wandb/
          values: test-configs/operator-wandb/

  test:
    name: Test Chart
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [
            "v1.32.2",
            "v1.31.6",
            "v1.30.10",
            "v1.29.14",
          ]
        configuration: [
            "default",
            "executor-enabled",
            "user-defined-secrets",
            "separate-pods",
            "runs-v2-bufstream",
            "weave-trace",
            "separate-pods-filemeta",
            "fmb",
          ]
    runs-on: ubuntu-latest
    environment: Helm Charts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
        with:
          version: v3.12.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          version: v0.27.0
          cluster_name: chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }}
          node_image: kindest/node:${{ matrix.k8s-version }}
        if: env.ACT || steps.list-changed.outputs.changed == 'true'

      - name: Install Minio
        run: kubectl --context kind-chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }} apply -f test-configs/minio/default.yaml
        if: env.ACT || steps.list-changed.outputs.changed == 'true'

      - name: Wait for Minio to be Ready
        run: kubectl --context kind-chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }} -n minio wait --for=condition=Ready pod/minio --timeout=300s
        if: env.ACT || steps.list-changed.outputs.changed == 'true'

      - name: Install pubsub and bigtable emulators
        run: |
          helm --kube-context kind-chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }} install pubsub-wandb-base ./charts/wandb-base --values test-configs/pubsub/values.yaml
          helm --kube-context kind-chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }} install bigtable-wandb-base ./charts/wandb-base --values test-configs/bigtable/values.yaml
        if: (env.ACT || steps.list-changed.outputs.changed == 'true') && matrix.configuration == 'fmb'

      - name: Apply user defined secrets
        run: |
          if [[ -d test-configs/additional-resources/${{matrix.configuration}} ]]; then
            kubectl --context kind-chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }} apply -f test-configs/additional-resources/${{matrix.configuration}}
          else
            echo "No additional resources to be applied for ${{matrix.configuration}}"
          fi
        if: env.ACT || steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        env:
          LICENSE: ${{ secrets.LICENSE }}
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install --namespace default \
          --charts ./charts/operator-wandb \
          --config ct.yaml \
          --helm-extra-args '--kube-context kind-chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }} --timeout 600s' \
          --helm-extra-set-args '--values test-configs/operator-wandb/${{ matrix.configuration }}.yaml --set=license=$LICENSE'
