name: Test operator-wandb Chart

on:
  pull_request:
    paths: charts/operator-wandb/**

jobs:
  test:
    name: Test Chart
    strategy:
      fail-fast: false
      matrix:
        k8s-version: ["v1.32.1", "v1.31.4", "v1.30.8"]
        configuration: ["default", "executor-enabled", "user-defined-secrets"]
    runs-on: ubuntu-latest
    environment: Helm Charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.4
        with:
          version: v3.16.3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: v3.11.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          version: v0.26.0
          cluster_name: chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }}
          node_image: kindest/node:${{ matrix.k8s-version }}
        if: env.ACT || steps.list-changed.outputs.changed == 'true'

      - name: Install Minio
        run: kubectl --context kind-chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }} apply -f test-configs/minio/default.yaml
        if: env.ACT || steps.list-changed.outputs.changed == 'true'

      - name: Wait for Minio to be Ready
        run: kubectl --context kind-chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }} -n minio wait --for=condition=Ready pod/minio --timeout=300s
        if: env.ACT || steps.list-changed.outputs.changed == 'true'

      - name: Apply user defined secrets
        run: kubectl --context kind-chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }} apply -f test-configs/additional-resources/${{matrix.configuration}}/*.yaml
        if: env.ACT || steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        env:
          LICENSE: ${{ secrets.LICENSE }}
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install \
          --charts ./charts/operator-wandb \
          --config ct.yaml \
          --helm-extra-args '--kube-context kind-chart-testing-${{ matrix.k8s-version }}-${{ matrix.configuration }} --timeout 600s' \
          --helm-extra-set-args '--values test-configs/operator-wandb/${{ matrix.configuration }}.yaml --set=license=$LICENSE'
