wandb_version: 1

epochs:
  desc: null
  value: 4
stringTest:
  desc: null
  value: A test config
dictTest:
  desc: null
  value:
    config_val: 2
    config_string: config string
listTest:
  desc: null
  value:
  - 0
  - one
  - '2'
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.19.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1755907195
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 3
      - 14
      - 16
      - 23
      - 61
      4: 3.11.6
      5: 0.19.4
      8:
      - 5
      13: darwin-arm64
